---
- name: Create volume for rancher
  docker_volume:
    name: rancher

- name: launch rancher on single node
  command: "docker run -d --restart=unless-stopped \
            -p 8080:8080 -p {{ rancher_ssl_port }}:443 \
            -v {{ certs_path }}/fullchain.pem:/etc/rancher/ssl/cert.pem \
            -v {{ certs_path }}/privkey.pem:/etc/rancher/ssl/key.pem \
            -v {{ certs_path }}/cert.pem:/etc/rancher/ssl/cacerts.pem \
            -v rancher:/var/lib/mysql \
            -v /host/rancher:/var/lib/rancher \
            --name={{ rancher_container_name }} rancher/rancher:latest"
  ignore_errors: true

- name: Get response from login endpoint using default password
  uri:
    url: '{{ rancher_url }}/v3-public/localProviders/local?action=login'
    method: POST
    body: {"username":"admin", "password":"admin"}
    status_code: 201
    body_format: json
    validate_certs: False
  register: login_result
  until: login_result.status == 201
  retries: 3
  delay: 10
  failed_when: login_result.status not in [201]
  ignore_errors: true
