---
- name: Register host
  hosts: localhost
  become: yes
  vars:
    server_eip: "rtest.outcatcher.com"
    ansible_ssh_private_key_file: "/tmp/{{ machine_key_name }}"
  tasks:
  - name: Register Rancher
    add_host:
      name: "Rancher"
      ansible_host: "{{ server_eip }}"
      ansible_ssh_user: "linux"

- name: Cron
  hosts: Rancher
  become: yes
  tasks:
  - name: Install Crontab
    apt:
      name:
        - cron

- name: Install certificates for rancher server
  hosts: Rancher
  become: yes
  roles:
    - role: geerlingguy.certbot
      vars:
        domain: rtest.outcatcher.com
        certbot_admin_email: "rancher@{{ domain }}"
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: []
        certbot_auto_renew_user: linux
        certbot_auto_renew_minute: "20"
        certbot_auto_renew_hour: "5"
        certbot_certs:
          - domains:
              - "{{ domain }}"

- name: Install Rancher
  hosts: Rancher
  become: yes
  vars:
    rancher_domain_name: rtest.outcatcher.com
  roles:
    - rancher