---
- name: Register host
  hosts: localhost
  become: yes
  vars:
    server_eip: "rtest.outcatcher.com"
    ansible_ssh_private_key_file: "/tmp/{{ machine_key_name }}"
  tasks:
  - name: Register Rancher
    add_host:
      name: "Rancher"
      ansible_host: "{{ server_eip }}"
      ansible_ssh_user: "linux"

- name: Install Rancher
  hosts: Rancher
  become: yes
  roles:
    - rancher